version: '3'

networks:
    bdnet:
      ipam:
        config:
          - subnet: 10.100.0.0/24

services: 
    rating-service:
        build: ./RatingService/
        restart: always
        depends_on: 
            - mongodb
        networks:
            bdnet:
                ipv4_address: 10.100.0.4    

    communication-service-dhaka:
        build: ./CommunicationService/
        # ports: 
        #     - 5001:5001
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.11
    
    ride-sharing-service-dhaka:
        build: ./RideSharingService/
        restart: always
        depends_on: 
            - communication-service-dhaka
        environment: 
            - SERVERLOCATION=dhaka
        networks:
            bdnet:
                ipv4_address: 10.100.0.12

    nginx-dhaka:
        build: ./nginx/
        # ports: 
        #     - 7000:80
        depends_on: 
            - rating-service
            - ride-sharing-service-dhaka
        environment: 
            - API_V1=ride-sharing-service-dhaka
            - API_V2=rating-service
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.10

    communication-service-chittagong:
        build: ./CommunicationService/
        # ports: 
        #     - 5002:5001
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.21
                
    ride-sharing-service-chittagong:
        build: ./RideSharingService/
        restart: always
        depends_on: 
            - communication-service-dhaka
        environment: 
            - SERVERLOCATION=chittagong
        networks:
            bdnet:
                ipv4_address: 10.100.0.22
            
    nginx-chittagong:
        build: ./nginx/
        # ports: 
        #     - 7000:80
        depends_on: 
            - rating-service
            - ride-sharing-service-chittagong
        environment: 
            - API_V1=ride-sharing-service-chittagong
            - API_V2=rating-service
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.20

    mongodb:
        image: mongo
        ports: 
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
        networks:
            bdnet:
                ipv4_address: 10.100.0.5
    
volumes:
    mongodb_data_container:
    
    
